language: minimal
dist: xenial

jobs:

  include:

    - stage: test
      script:
        - make dev
        - make check-format
        - make lint
        - make test

    - stage: build
      if: branch != master
      script:
        - make prod

    - stage: push
      if: branch = master
      script:
        - make prod
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make push

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
