main:
    auth_token: 
    admins:
        ids: []
        roles: []
    postgres:
        user:
        password:
        name:
        host:
        port: 5432
    mongodb:
        user:
        password:
        name:
        host:
        port: 27017
    rabbitmq:
        user:
        password:
        host:
        vhost: "/"
        port: 5672
    api_keys:
        google_cse:
        google:
        giphy:
        news:
        wolfram:
        open_weather:
    logging:
        queue_enabled: True
        block_discord_send: False
    disabled_plugins: ["kanye"]
    default_prefix: "."
    config_cache_reset: 30

# Special things
special:
