main:
    required:
        command_prefix: "."
        auth_token: 
    optional:
        game: RuneScape
    admins:
        ids: []
        roles: []
    database:
        user: admin
        password: admin
        name: basement_bot
        host: db
        prefix: postgres
        port: 5432
    disabled_plugins: []

plugins:
    urban:
        responses_max: 3
    grab:
        grabs_max: 3
        invalid_channels: []
    factoids:
        prefix: "?"
        list_all_max: 5
        loop_update_minutes: 15
    google:
        cse_id:
        dev_key:
    giphy:
        dev_key:
    kanye:
        channel:
        min_hours:
        max_hours:
        on_start: True
    news:
        channel:
        api_key:
        cron_config: "0 17 * * *"
        country: US
        prefer: [
            "CNN",
            "CBS",
            "NBC",
            "FOX"
        ]
    relay:
        mq_host:
        mq_vhost:
        mq_port:
        mq_user:
        mq_pass:
        channel_map: {}
        mq_send_queue:  DiscordToIRC
        mq_recv_queue: IRCToDiscord
        discord_ban_days: 14
        stale_seconds: 600
        publish_seconds: 2
        consume_seconds: 2
        commands_allowed: True
        response_limit: 3
        send_limit: 3
        notice_errors: True
    protect:
        included_channels: []
        stringMap:
            "bad word/sentence here":
                message: That is a bad word/sentence!
                delete: true
                private: false
                sensitive: true
        length_limit: 500
    logger:
        channel_map: {}
        embed_color: 0xF1C40F
    weather:
        dev_key: 
        units: imperial
    duck:
        channel: 
        min_hours: 1
        max_hours: 2
        on_start: False
        timeout_seconds: 30
        cooldown_seconds: 10
        success_percent: 80
    wolfram:
        api_key:
    spotify:
        client_id:
        client_secret:
