version: '3'

services:

    bot:
        image: effprime/basement-bot:latest
        container_name: basement_bot
        env_file: .env
        environment:
            - DEBUG=0
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        container_name: basement_bot_db
        volumes:
            - db_volume:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASS=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

volumes:
    db_volume: